# Generated by Django 4.2.6 on 2023-10-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFam_App', '0002_recipe_rating_group_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
