# Generated by Django 4.2.6 on 2023-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFam_Backend', '0004_alter_comment_user_alter_group_admins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
            ],
        ),
    ]
