# Generated by Django 4.2.6 on 2023-10-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFam_Backend', '0008_group_members_alter_group_admins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
    ]
