# Generated by Django 4.2.6 on 2023-11-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFam_Backend', '0010_profile_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(max_length=4000),
        ),
    ]
